[CmdletBinding()]
param(
  [int]$InactivityDays = 14,
  [int]$DoneGraceDays = 1,
  [int]$CandidateDays = 2
)

$ErrorActionPreference = 'Stop'

$root     = Split-Path -Parent $PSScriptRoot
$current  = Join-Path $root 'current'
$old      = Join-Path $root 'old'
$core     = Join-Path $root 'core'
$reports  = Join-Path $root 'reports'
$archive  = Join-Path $PSScriptRoot 'archive.ps1'

foreach ($dir in @($current, $old, $core, $reports)) {
  if (-not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
  }
}

function Get-Meta {
  param([string]$Path)

  $tags = ''
  $topic = ''
  $type = ''
  $summary = ''

  $lines = Get-Content -LiteralPath $Path -TotalCount 20
  $inFrontMatter = $false

  foreach ($line in $lines) {
    if ($line -eq '---') {
      if ($inFrontMatter) { break }
      $inFrontMatter = $true
      continue
    }

    if ($inFrontMatter -and $line -match '^tags:\s*\[(.*)\]')   { $tags = $Matches[1].Trim() }
    if ($inFrontMatter -and $line -match '^topic:\s*(.*)')      { $topic = $Matches[1].Trim() }
    if ($inFrontMatter -and $line -match '^type:\s*(.*)')       { $type = $Matches[1].Trim() }
    if ($inFrontMatter -and $line -match '^summary:\s*(.*)')    { $summary = $Matches[1].Trim() }
  }

  [pscustomobject]@{
    Type    = $type
    Topic   = $topic
    Tags    = $tags
    Summary = $summary
  }
}

$today = (Get-Date).Date

if (Test-Path -LiteralPath $archive) {
  & $archive -InactivityDays $InactivityDays -DoneGraceDays $DoneGraceDays
} else {
  throw "archive.ps1 not found: $archive"
}

$candidates = @()
Get-ChildItem -LiteralPath $current -Filter '*.md' -File | ForEach-Object {
  $fileDate = if ($_.BaseName -match '^(\d{4})-(\d{2})-(\d{2})_') {
    [datetime]::new([int]$Matches[1], [int]$Matches[2], [int]$Matches[3])
  } else {
    $_.LastWriteTime.Date
  }

  $age = ($today - $fileDate).Days
  if ($age -ge $CandidateDays) {
    $m = Get-Meta -Path $_.FullName
    $candidates += [pscustomobject]@{
      Name    = $_.Name
      Age     = $age
      Topic   = $m.Topic
      Tags    = $m.Tags
      Summary = $m.Summary
    }
  }
}

$reportPath = Join-Path $reports "promotion-candidates-$(Get-Date -Format 'yyyy-MM-dd').md"

$out = @(
  '# Promotion Candidates',
  '',
  'Auto-generated by consolidate.ps1. Do not edit by hand.',
  '',
  'These are `current/` session notes old enough that they should either be promoted to `core/` or left to archive.',
  '',
  "Generated: $((Get-Date).ToString('yyyy-MM-dd HH:mm:ss')) | CandidateDays: $CandidateDays",
  ''
)

if ($candidates.Count -eq 0) {
  $out += '_No candidates._'
} else {
  foreach ($c in ($candidates | Sort-Object Age -Descending)) {
    $meta = @()
    if ($c.Topic)   { $meta += "topic: $($c.Topic)" }
    if ($c.Tags)    { $meta += "tags: $($c.Tags)" }
    if ($c.Summary) { $meta += $c.Summary }

    $line = "- **$($c.Name)** ($($c.Age) days)"
    if ($meta.Count -gt 0) { $line += " — $($meta -join ' | ')" }
    $out += $line

    $topic = if ($c.Topic) {
      ($c.Topic.ToLower() -replace '[^a-z0-9\-_]+', '_').Trim('_')
    } else {
      'topic'
    }

    $promoteCmd = "pwsh -NoProfile -File $PSScriptRoot\promote-memory.ps1 -FileName `"$($c.Name)`" -NewName `"$topic`""

    $out += '```powershell'
    $out += $promoteCmd
    $out += '```'
    $out += ''
  }
}

$out | Set-Content -LiteralPath $reportPath -Encoding utf8

Write-Output "Consolidation complete. Archived older notes; promotion candidates: $($candidates.Count). Report: $reportPath"
